version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:<< parameters.go-version >>
    parameters:
      go-version:
        type: string
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/hashicorp/terraform-config-inspect
    steps:
      - checkout
      - run: go test
      - run: go install .

workflows:
  terraform-config-inspect:
    jobs:
      - test:
          matrix:
            parameters:
              go-version: ["1.11.13", "1.13.4"]
          name: test-go-<< matrix.go-version >>
